# **Fake News Model Training**

# All Imports Here

In [13]:
import os

os.chdir('d:\\GitHub\\TECH_405_Fake_News_Indicator_ANN')
os.getcwd()

'd:\\GitHub\\TECH_405_Fake_News_Indicator_ANN'

In [14]:
import pandas as pd
from Data_Preprocessor.preprocessor import DataPreprocessor

# Dataset Import

In [15]:
df = pd.read_csv('data\\news.csv')
df = df.reset_index()
df = df.drop(['index', 'Unnamed: 0'], axis=1)

In [16]:
df.head()

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [17]:
df.shape

(6335, 3)

In [18]:
df.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(29)

In [20]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

# Applying Preprocessor

In [21]:
dp = DataPreprocessor(df, cols=['title', 'text'])
df_clean = dp.run_preprocessor()

In [22]:
df_clean.head()

,title,title_clean,text,text_clean
0,you can smell hillary s fear,"[smell, hillary, fear]",daniel greenfield a shillman journalism fellow...,"[daniel, greenfield, shillman, journalism, fel..."
1,watch the exact moment paul ryan committed pol...,"[watch, exact, moment, paul, ryan, committed, ...",google pinterest digg linkedin reddit stumbleu...,"[google, pinterest, digg, linkedin, reddit, st..."
2,kerry to go to paris in gesture of sympathy,"[kerry, go, paris, gesture, sympathy]",u s secretary of state john f kerry said monda...,"[u, secretary, state, john, f, kerry, said, mo..."
3,bernie supporters on twitter erupt in anger ag...,"[bernie, supporter, twitter, erupt, anger, dnc...",kaydee king november the lesson from tonight s...,"[kaydee, king, november, lesson, tonight, dem,..."
4,the battle of new york why this primary matters,"[battle, new, york, primary, matter]",it s primary day in new york and front runners...,"[primary, day, new, york, front, runner, hilla..."

In [23]:
df_clean.isnull().sum()

title          0
title_clean    0
text           0
text_clean     0
dtype: int64

In [24]:
# dropping unnecessary cols
df_clean.drop(['title', 'text'], axis = 1, inplace=True)
df_clean['combined_text'] = dp.combine_text()
df_clean['label'] = df['label'].copy()
df_clean['label'] = df_clean['label'].map({'FAKE': 0, 'REAL': 1})
df_clean.head()

,title_clean,text_clean,combined_text,label
0,"[smell, hillary, fear]","[daniel, greenfield, shillman, journalism, fel...",smell hillary fear daniel greenfield shillman ...,0
1,"[watch, exact, moment, paul, ryan, committed, ...","[google, pinterest, digg, linkedin, reddit, st...",watch exact moment paul ryan committed politic...,0
2,"[kerry, go, paris, gesture, sympathy]","[u, secretary, state, john, f, kerry, said, mo...",kerry go paris gesture sympathy u secretary st...,1
3,"[bernie, supporter, twitter, erupt, anger, dnc...","[kaydee, king, november, lesson, tonight, dem,...",bernie supporter twitter erupt anger dnc tried...,0
4,"[battle, new, york, primary, matter]","[primary, day, new, york, front, runner, hilla...",battle new york primary matter primary day new...,1

# Modeling

## **RNN**

## **LSTM**